[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
      
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/resend/emails"
  to = "/.netlify/functions/resend-emails"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200