[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
      
[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_RESEND_API_KEY = "${VITE_RESEND_API_KEY}"

[context.deploy-preview.environment]
  VITE_RESEND_API_KEY = "${VITE_RESEND_API_KEY}"

[context.branch-deploy.environment]
  VITE_RESEND_API_KEY = "${VITE_RESEND_API_KEY}"

[[redirects]]
  from = "/.netlify/functions/resend-emails"
  to = "/.netlify/functions/resend-emails"
  status = 200
  force = true

[[redirects]]
  from = "/api/resend/emails"
  to = "/.netlify/functions/resend-emails"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200